spots-api/map/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from map.views import MapView
from map.api import SpotsApi, SpotApi, RatingsApi, VotesApi

app_name = 'map'
urlpatterns = [
    path('', MapView.as_view(), name='index'),

    path('spots/',                              SpotsApi.as_view()),
    path('spots/<int:spot_id>/',                SpotApi.as_view()),
    path('spots/<int:spot_id>/ratings/',        RatingsApi.as_view()),
    path('spots/<int:spot_id>/votes/',          VotesApi.as_view()),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spots-api/spots-api/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('map/', include('map.urls')),
    path('admin/', admin.site.urls),
]

spots-api/map/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Spot(models.Model):

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        spot = "Spot %s - %s: %s" % (self.id, self.name, self.description)
        return spot

    def get_score(self):
        votes = Vote.objects.filter(spot=self.id)

        score = 0
        for vote in votes:
            score += 1 if vote.positive else -1

        return score

    def get_ratings_dict(self):
        ratings = Rating.objects.filter(spot=self.id)

        ratings_dict = {}
        for rating in ratings:
            if rating.rating_type.name in ratings_dict:
                ratings_dict[rating.rating_type.name] += rating.score
            else:
                ratings_dict[rating.rating_type.name] = rating.score

        for rating_type, score in ratings_dict.items():
            ratings_dict[rating_type] = round((score / ratings.count()), 2)

        return ratings_dict

class RatingType(models.Model):

    name = models.CharField(max_length=50)

    def __str__(self):
        rating_type = self.name
        return rating_type

class Rating(models.Model):

    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    rating_type = models.ForeignKey(RatingType, on_delete=models.CASCADE)
    score = models.IntegerField(
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ]
    )

class Vote(models.Model):

    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    positive = models.BooleanField()

spots-api/map/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from map.models import Spot, Rating, Vote

class SpotForm(ModelForm):
    class Meta:
        model = Spot
        fields = ['name', 'description', 'latitude', 'longitude']
        widgets = {
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
        }

class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['spot', 'rating_type', 'score']
        widgets = {
            'spot': forms.HiddenInput(),
            'rating_type': forms.HiddenInput(),
        }

class VoteForm(ModelForm):
    class Meta:
        model = Vote
        fields = ['positive']
        widgets = {
            'positive': forms.HiddenInput(),
        }

spots-api/map/views.py
from django.shortcuts import render
from django.views import View

class MapView(View):
    def get(self, request):
        return render(request, 'map/index.html')

spots-api/map/templates/map/create.html
<div class='form'>
	<h2>Create Spot</h2>
	<form action="{% url 'map:index' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type='submit' value='Create'>
	</form>
</div>

spots-api/map/templates/map/downvote.html
<form action="{% url 'map:votes' spot_id %}" method="post">
	{% csrf_token %}
	{{ form }}
	<input type='submit' value='-1'>
</form>

spots-api/map/templates/map/failure.html
<div id='main'>
	<p>Failed. Please try again.</p>
    <a href="{% url 'map:index' %}">Back to nearby spots.</a>
</div>

spots-api/map/templates/map/get.html
<div class='spot'>
    <h2>{{ spot.name }}</h2>
    <p>{{ spot.description }}</p>
    {% for info in rating_info %}
        <h3>{{ info.0 }}</h3>
        <p>{{ info.1 }}/10</p>
        <div class='form'>
            <form action="{% url 'map:ratings' spot.id %}" method="post">
                {% csrf_token %}
                {{ info.2 }}
                <input type='submit' value='Rate'>
            </form>
        </div>
    {% endfor %}
    <div class='voting'>
        <form action="{% url 'map:votes' spot.id %}" method="post">
            {% csrf_token %}
            {{ downvote_form }}
            <input type='submit' value='-1'>
        </form>
        {{ score }}
        <form action="{% url 'map:votes' spot.id %}" method="post">
            {% csrf_token %}
            {{ upvote_form }}
            <input type='submit' value='+1'>
        </form>
    </div>
</div>

spots-api/map/templates/map/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'map/css/style.css' %}" />
<script type="text/javascript" src="{% static 'map/js/map.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACXUGHA7tiOrgVTmGff88LgfLr47oLDFI&callback=initMap" async defer></script>
<div id='main'>
    <div id='map'>
    </div>
</div>

spots-api/map/templates/map/ratings.html
<div class='form'>
	<h3>Ratings</h3>
	<form action="{% url 'map:ratings' %}" method="post">
		{% csrf_token %}
		{% for form in forms %}
			{{ form }}
			<input type='submit' value='Rate'>
		{% endfor %}
	</form>
</div>

spots-api/map/templates/map/success.html
<div id='main'>
	<p>Success!</p>
    <a href="{% url 'map:index' %}">Back to nearby spots.</a>
</div>

spots-api/map/templates/map/upvote.html
<form action="{% url 'map:votes' spot_id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type='submit' value='+1'>
</form>